#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
carpentry: 'dc'

# Overall title for pages.
title: 'IRIM R Workshops'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: '2026-02-09'

# Comma-separated list of keywords for the lesson
keywords: 'tidyverse,  data-wrangling, data-carpentry, R'
#'ggplot2, tidyverse, data-visualization, data-visualisation, data-wrangling, data-carpentry, R'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/kathrynnapier/irim-r-workshops/'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'Napier.k@irim.mn'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes:
- introduction-r-rstudio.Rmd
- introduction-r-packages-markdown.Rmd
- starting-with-data.Rmd
#- visualizing-ggplot.Rmd
#- how-r-thinks-about-data.Rmd
#- working-with-data.Rmd

# Information for Learners
learners:
- reference.md

# Information for Instructors
instructors:
#- instructor-notes.md

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live

url: 'https://kathrynnapier.github.io/irim-r-workshops/'
analytics: carpentries
lang: en

