name: "Build and Deploy Mongolian Site"
description: "Build and deploy the Mongolian text version of the workshop website using the carpentries/workbench-docker container"

on:
  push:
    branches:
      - 'mn'
    paths-ignore:
      - '.github/workflows/**.yaml'
      - '.github/workbench-docker-version.txt'
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build?'
        required: true
        default: 'Maintainer (via GitHub)'
      reset:
        description: 'Reset cached markdown files'
        required: true
        default: false
        type: boolean

concurrency:
  group: docker-build-deploy-mn
  cancel-in-progress: true

jobs:
  full-build:
    name: "Build Full Mongolian Site"
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pages: write
      id-token: write
    container:
      image: ghcr.io/carpentries/workbench-docker:${{ vars.WORKBENCH_TAG || 'latest' }}
      env:
        WORKBENCH_PROFILE: "ci"
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        RENV_PATHS_ROOT: /home/rstudio/lesson/renv
        RENV_PROFILE: "lesson-requirements"
        RENV_CONFIG_EXTERNAL_LIBRARIES: "/usr/local/lib/R/site-library"
      volumes:
        - ${{ github.workspace }}:/home/rstudio/lesson
      options: --cpus 1
    steps:
      - name: "Checkout mn branch"
        uses: actions/checkout@v4
        with:
          ref: mn

      - name: "Mark Repository as Safe"
        run: git config --global --add safe.directory $(pwd)
        shell: bash

      - name: "Setup Lesson Dependencies"
        id: build-container-deps
        uses: carpentries/actions/build-container-deps@main
        with:
          CACHE_VERSION: ${{ vars.CACHE_VERSION || '' }}
          WORKBENCH_TAG: ${{ vars.WORKBENCH_TAG || 'latest' }}
          LESSON_PATH: ${{ vars.LESSON_PATH || '/home/rstudio/lesson' }}
          role-to-assume: ${{ secrets.AWS_GH_OIDC_ARN }}
          aws-region: ${{ secrets.AWS_GH_OIDC_REGION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and Deploy Mongolian Site"
        uses: carpentries/actions/build-and-deploy@main
        with:
          reset: ${{ vars.BUILD_RESET || github.event.inputs.reset || 'false' }}
          skip-manage-deps: ${{ steps.build-container-deps.outputs.renv-cache-available || steps.build-container-deps.outputs.backup-cache-used || 'false' }}
          lang-code: 'mn'
